symfony/src/Entity/Workshop.php
<?php

namespace App\Entity;

use App\Repository\WorkshopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkshopRepository::class)
 */
class Workshop
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $startsAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endsAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $capacity;

    /**
     * @ORM\ManyToOne(targetEntity=Program::class, inversedBy="workshops")
     * @ORM\JoinColumn(nullable=false)
     */
    private $program;

    /**
     * @ORM\Column(type="integer")
     */
    private $statusCode;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : 0})
     */
    private $currentRegistered;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="workshops")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getStartsAt(): ?\DateTimeInterface
    {
        return $this->startsAt;
    }

    public function setStartsAt(?\DateTimeInterface $startsAt): self
    {
        $this->startsAt = $startsAt;

        return $this;
    }

    public function getEndsAt(): ?\DateTimeInterface
    {
        return $this->endsAt;
    }

    public function setEndsAt(?\DateTimeInterface $endsAt): self
    {
        $this->endsAt = $endsAt;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getProgramImageFilename()
    {
        return 'images/programs/'.$this->program->getImageFilename();
    }

    public function getStatusCode(): ?int
    {
        $this->workshopStatusCode();

        return $this->statusCode;
    }

    public function setStatusCode(int $statusCode = null): self
    {
        $this->workshopStatusCode();

        return $this;
    }

    public function workshopStatusCode()
    {
        $now = new \DateTime();

        if ($now >= $this->getStartsAt() && $now <= $this->getEndsAt()) {
            $this->statusCode = 0; // Ongoing event
        } else if ($now > $this->getEndsAt()) {
            $this->statusCode = -1; // Past event
        } else if ($now < $this->getStartsAt()) {
            $this->statusCode = 1; // Future event
        }
    }

    public function getCurrentRegistered(): ?int
    {
        return $this->currentRegistered;
    }

    public function setCurrentRegistered(int $currentRegistered): self
    {
        $this->currentRegistered = $currentRegistered;

        return $this;
    }

    public function getRemainingCapacity(): ?int
    {
        return $this->capacity - $this->currentRegistered;
    }

    public function getCapacityPercentage()
    {
        return round($this->currentRegistered / $this->capacity * 100);
    }

    public function addCurrentRegistered()
    {
        $this->currentRegistered++;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addWorkshop($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeWorkshop($this);
        }

        return $this;
    }
}

symfony/templates/_admin_primary_btns.html.twig
<div class="col-sm-4">
    <a href="{{ path('admin_workshop_create') }}" class="btn btn-danger btn-rounded mb-3 mr-3">
        <i class="mdi mdi-plus"></i> 
        Create Workshop
    </a>

    <button class="btn btn-primary btn-rounded mb-3" data-bs-toggle="modal" data-bs-target="#standard-modal"> 
        <i class="mdi mdi-account-multiple"></i> 
        Impersonation
    </button>

    {{ include('workshop_admin/_admin_impersonate_modal.html.twig')}}

</div>

symfony/templates/_leftside_bar.html.twig
<div class="leftside-menu leftside-menu-detached show">
    <div class="leftbar-user">
        <a href="#">
            <img src="{{ asset('images/profile/alien.png') }}" alt="user-image" height="42" class="rounded-circle shadow-sm">
            <span class="leftbar-user-name">Dominic Keller</span>
        </a>
    </div>
    <ul class="side-nav">
        <li class="side-nav-title side-nav-item">Navigation</li>
        <li class="side-nav-item">
            <a data-bs-toggle="collapse" href="#sidebarDashboards" aria-expanded="false" aria-controls="sidebarDashboards" class="side-nav-link">
                <i class="uil-home-alt"></i>
                <span class="badge bg-info rounded-pill float-end">4</span>
                <span> Dashboards </span>
            </a>
            <div class="collapse" id="sidebarDashboards">
                <ul class="side-nav-second-level">
                    <li>
                        <a href="dashboard-analytics.html">Analytics</a>
                    </li>
                    <li>
                        <a href="dashboard-crm.html">CRM</a>
                    </li>
                    <li>
                        <a href="dashboard-projects.html">Projects</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="side-nav-title side-nav-item">Apps</li>
        <li class="side-nav-item">
            <a href="apps-calendar.html" class="side-nav-link">
                <i class="uil-calender"></i>
                <span> Calendar </span>
            </a>
        </li>
        <li class="side-nav-item">
            <a data-bs-toggle="collapse" href="#sidebarEmail" aria-expanded="false" aria-controls="sidebarEmail" class="side-nav-link">
                <i class="uil-envelope"></i>
                <span> Email </span>
                <span class="menu-arrow"></span>
            </a>
            <div class="collapse" id="sidebarEmail">
                <ul class="side-nav-second-level">
                    <li>
                        <a href="apps-email-inbox.html">Inbox</a>
                    </li>
                    <li>
                        <a href="apps-email-read.html">Read Email</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="side-nav-item">
            <a data-bs-toggle="collapse" href="#sidebarProjects" aria-expanded="false" aria-controls="sidebarProjects" class="side-nav-link">
                <i class="uil-briefcase"></i>
                <span> Workshops </span>
                <span class="menu-arrow"></span>
            </a>
            <div class="collapse show" id="sidebarProjects">
                <ul class="side-nav-second-level">
                    <li class="menuitem-active">
                        <a href="#" class="active">List</a>
                    </li>
                    <li>
                        <a href="#">Details</a>
                    </li>
                    <li>
                        <a href="#">Gantt <span class="badge rounded-pill badge-dark-lighten text-dark font-10 float-end">New</span></a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="side-nav-item">
            <a data-bs-toggle="collapse" href="#sidebarTasks" aria-expanded="false" aria-controls="sidebarTasks" class="side-nav-link">
                <i class="uil-clipboard-alt"></i>
                <span> Tasks </span>
                <span class="menu-arrow"></span>
            </a>
            <div class="collapse" id="sidebarTasks">
                <ul class="side-nav-second-level">
                    <li>
                        <a href="apps-tasks.html">List</a>
                    </li>
                    <li>
                        <a href="apps-tasks-details.html">Details</a>
                    </li>
                    <li>
                        <a href="apps-kanban.html">Kanban Board</a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</div>

symfony/templates/_page_title.html.twig
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="#">{{ breadcrumb_primary }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ path('homepage') }}">{{ breadcrumb_second }}</a></li>
                    <li class="breadcrumb-item active">{{ breadcrumb_active }}</li>
                </ol>
            </div>
            <h4 class="page-title">{{ page_title }}</h4>
        </div>
    </div>
</div>

symfony/templates/_pagetitle.html.twig
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="#">{{ breadcrumb_primary }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ path('app_home') }}">{{ breadcrumb_second }}</a></li>
                    <li class="breadcrumb-item active">{{ breadcrumb_active }}</li>
                </ol>
            </div>
            <h4 class="page-title">{{ page_title }}</h4>
        </div>
    </div>
</div>     
<!-- end page title --> 

symfony/templates/_workshop_filter.html.twig
<div class="col-sm-{{ is_granted('ROLE_ADMIN') ? '8' : '12' }}">
    <div class="text-sm-end">
        <div class="btn-group mb-3">
            <button type="button" class="btn btn-primary">All</button>
        </div>
        <div class="btn-group mb-3 ms-1">
            <button type="button" class="btn btn-light">Ongoing</button>
            <button type="button" class="btn btn-light">Finished</button>
        </div>
        <div class="btn-group mb-3 ms-2 d-none d-sm-inline-block">
            <button type="button" class="btn btn-secondary"><i class="dripicons-view-apps"></i></button>
        </div>
        <div class="btn-group mb-3 d-none d-sm-inline-block">
            <button type="button" class="btn btn-link text-muted"><i class="dripicons-checklist"></i></button>
        </div>
    </div>
</div>

symfony/templates/base.html.twig
<!doctype html>
<html lang="en">

    <head>

        <title>{% block title %}Les Mills Workshop Register ∙ Les Mills Asia Pacific{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <link rel="stylesheet" href="{{ asset('css/icons.min.css') }}" type="text/css">
            <link rel="stylesheet" href="{{ asset('css/app-modern.min.css') }}" type="text/css" id="light-style">
        {% endblock %}

    </head>

    <body class="show" data-layout="detached" data-layout-config="{leftSidebarCondensed:false, darkMode:false, showRightSidebarOnStart: true}" style="visibility: visible;" data-new-gr-c-s-check-loaded="14.1026.0" data-gr-ext-installed="">

        {% block top_navbar %}
            <div class="navbar-custom topnav-navbar topnav-navbar-dark">
                <div class="container-fluid">
                    {{ include('navbar/navbar_left.html.twig')}}
                    {{ include('navbar/navbar_right.html.twig')}}
                </div>
            </div>
        {% endblock %}

        {# Impersonation #}
        {% if is_granted('ROLE_PREVIOUS_ADMIN') %}
            <div class="alert alert-warning" style="margin-bottom: 0;">
                You are currently switched to this user.
                <a href="{{ path('homepage', {
                    '_switch_user': '_exit'
                }) }}">Exit Impersonation</a>
            </div>
        {% endif %}
        
        {# Messages - must be under top_navbar #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {% block main_content %}
            <div class="container-fluid">
                <div class="wrapper menuitem-active">

                    {% block sidebar_left %}
                        {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_INSTRUCTOR') %}
                            {% if app.user.username is defined %}
                                {{ include('navbar/sidebar_left.html.twig', { 'username': app.user.username }) }}
                            {% else %}
                                {{ include('navbar/sidebar_left.html.twig', { 'username': '' }) }}
                            {% endif %}
                        {% endif %}
                    {% endblock %}

                    
                    <div class="content-page">

                        <div class="content">

                            {% block page_title %}{% endblock %}

                            {# Usually rewrite this one unless it is a form #}
                            {% block content_block %}
                                <div class="row">
                                    <div class="col-12">

                                        {% block form_content %}
                                            <div class="card">
                                                <div class="card-body">
                                                    {% block form %}{% endblock %}
                                                </div>
                                            </div>
                                        {% endblock %}

                                    </div>
                                </div>
                            {% endblock %}

                        </div>

                        {% block footer_innerpage %}
                            {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_INSTRUCTOR') %}
                                {{ include('footer.html.twig')}}
                            {% endif %}
                        {% endblock %}

                    </div>
                </div>
            </div>
        {% endblock %}

        {% block footer_homepage %}
            {% if not is_granted('ROLE_ADMIN') and not is_granted('ROLE_INSTRUCTOR')  %}
                {{ include('footer.html.twig')}}
            {% endif %}
        {% endblock %}

        {# JavaScript #}
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
            <script src="{{ asset('js/app.min.js') }}"></script>
            <script src="{{ asset('js/vendor.min.js') }}"></script>
        {% endblock %}

    </body>
</html>

symfony/templates/footer.html.twig
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Les Mills Asia Pacific
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>

symfony/templates/footer_homepage.html.twig
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <script>document.write(new Date().getFullYear())</script> © Les Mills Asia Pacific
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>

symfony/templates/homepage.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" href="{{ asset('css/algolia-autocomplete.css') }}">
{% endblock %}

{% block page_title %}
    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_INSTRUCTOR') %}
        {{ include('_page_title.html.twig', {
            breadcrumb_primary: 'Hyper',
            breadcrumb_second: 'Workshops',
            breadcrumb_active: 'Workshop List',
            page_title: 'Workshops'
        })}}
    {% else %}
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                    </div>
                    <h4 class="page-title"></h4>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block content_block %}

    {% block workshop_toolkit %}
        <div class="row mb-2">
            {% if is_granted('ROLE_ADMIN')%}
                {{ include('_admin_primary_btns.html.twig')}}
            {% endif %}

            {{ include('_workshop_filter.html.twig')}}
        </div>
    {% endblock %}

    {% block workshop_list %}
        <div class="row">
            {{ include('workshop_list.html.twig')}}
        </div>
    {% endblock %}
    
{% endblock %}

{% block javascripts %}
    {{ parent() }}

    <script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script>
    <script src="{{ asset('js/algolia-autocomplete.js') }}"></script>
{% endblock %}

symfony/templates/workshop_list.html.twig
{% for workshop in workshops %}
    <div class="col-lg-6 col-xl-4 col-xxl-3">
        <div class="card d-block">
            <div class="card-body">

                {% if is_granted('ROLE_ADMIN') %}
                    {{ include('workshop/_admin_secondary_btns.html.twig')}}
                {% endif %}

                {% block main_workshop_content %}
                    <img class="card-img mb-2" src="{{ asset(workshop.programImageFilename) }}" style="width: 100px; height: 40px;" alt="project image cap">
                    <h4 class="mt-0"> 
                        <a href="{{ path('workshop_detail', { id:workshop.id }) }}" class="text-title">{{ workshop.name }}</a>
                    </h4>
                    <div class="badge bg-success mb-3">Finished</div>
                
                    <p class="text-muted font-13 mb-3">
                        With supporting text below as a natural lead-in to additional contenposuere erat a ante...
                        <a href="#" class="fw-bold text-muted">view more</a>
                    </p>

                    <span class="pe-2 text-nowrap mb-2 d-inline-block">
                        <i class="uil-location-pin-alt text-muted"></i>
                        {{ workshop.location }}
                    </span>

                    <span class="text-nowrap mb-2 d-inline-block">
                        <i class="mdi mdi-comment-multiple-outline text-muted"></i>
                        Online Live Stream
                    </span>
                
                    <br>

                    <span class="pe-2 text-nowrap mb-2 d-inline-block text-primary">
                        <i class="mdi mdi-calendar-start text-muted"></i>
                        <strong> {{ workshop.startsAt|date('Y-m-d H:i') }} </strong>
                    </span>

                    <br>

                    <span class="text-nowrap mb-2 d-inline-block">
                        <i class="mdi mdi-calendar-end text-muted"></i>
                        <strong> {{ workshop.endsAt|date('Y-m-d H:i') }} </strong>
                    </span>

                    <br>

                    <span> 
                        <i class="uil-pricetag-alt text-muted"></i>
                        <strong> Free </strong>
                    </span>

                    <p class="mb-1 proggress-toolbox">

                        <span class="workshop-capacity-status text-nowrap mb-2 d-inline-block">
                            <div class="mb-2 fw-bold">
                                <i class="mdi mdi-account-group text-muted"></i>
                                <strong> {{ workshop.capacity }} </strong> Vacancies

                                <span class="float-end text-dark">{{ workshop.capacityPercentage }}% sold out</span>
                            </div>

                            <div class="progress progress-sm">
                                <div class="progress-bar" role="progressbar" aria-valuenow="{{ workshop.capacityPercentage }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ workshop.capacityPercentage }}%;"></div>
                            </div>
                        </span>

                        <br>

                        <div class="workshop-participants">
                            <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="Mat Helme" class="d-inline-block">
                                <img src="{{ asset('images/profile/alien.png') }}" class="rounded-circle avatar-xs" alt="friend">
                            </a>
                            <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="Michael Zenaty" class="d-inline-block">
                                <img src="{{ asset('images/profile/astronaut.png') }}" class="rounded-circle avatar-xs" alt="friend">
                            </a>

                            <a href="#" class="d-inline-block text-dark fw-bold ms-2">
                                +{{ workshop.currentRegistered - 2 }} more
                            </a>
                        </div>

                        {% if is_granted('ROLE_INSTRUCTOR') %}
                            {{ include('workshop/_instructor_control.html.twig')}}
                        {% endif %}
                    </p>
                {% endblock %}

            </div>
        </div>
    </div>
{% endfor %}