symfony/src/Entity/Workshop.php
<?php

namespace App\Entity;

use App\Repository\WorkshopRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkshopRepository::class)
 */
class Workshop
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $startsAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $endsAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $capacity;

    /**
     * @ORM\ManyToOne(targetEntity=Program::class, inversedBy="workshops")
     * @ORM\JoinColumn(nullable=false)
     */
    private $program;

    /**
     * @ORM\Column(type="integer")
     */
    private $statusCode;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : 0})
     */
    private $currentRegistered;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="workshops")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getStartsAt(): ?\DateTimeInterface
    {
        return $this->startsAt;
    }

    public function setStartsAt(?\DateTimeInterface $startsAt): self
    {
        $this->startsAt = $startsAt;

        return $this;
    }

    public function getEndsAt(): ?\DateTimeInterface
    {
        return $this->endsAt;
    }

    public function setEndsAt(?\DateTimeInterface $endsAt): self
    {
        $this->endsAt = $endsAt;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getProgram(): ?Program
    {
        return $this->program;
    }

    public function setProgram(?Program $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getProgramImageFilename()
    {
        return 'images/programs/'.$this->program->getImageFilename();
    }

    public function getStatusCode(): ?int
    {
        $this->workshopStatusCode();

        return $this->statusCode;
    }

    public function setStatusCode(int $statusCode = null): self
    {
        $this->workshopStatusCode();

        return $this;
    }

    public function workshopStatusCode()
    {
        $now = new \DateTime();

        if ($now >= $this->getStartsAt() && $now <= $this->getEndsAt()) {
            $this->statusCode = 0; // Ongoing event
        } else if ($now > $this->getEndsAt()) {
            $this->statusCode = -1; // Past event
        } else if ($now < $this->getStartsAt()) {
            $this->statusCode = 1; // Future event
        }
    }

    public function getCurrentRegistered(): ?int
    {
        return $this->currentRegistered;
    }

    public function setCurrentRegistered(int $currentRegistered): self
    {
        $this->currentRegistered = $currentRegistered;

        return $this;
    }

    public function getRemainingCapacity(): ?int
    {
        return $this->capacity - $this->currentRegistered;
    }

    public function getCapacityPercentage()
    {
        return round($this->currentRegistered / $this->capacity * 100);
    }

    public function addCurrentRegistered()
    {
        $this->currentRegistered++;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addWorkshop($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeWorkshop($this);
        }

        return $this;
    }
}

symfony/src/Controller/WorkshopController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use App\Entity\Workshop;
use Symfony\Component\Mailer\MailerInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request as Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\WorkshopRepository;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mime\Email;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class WorkshopController extends AbstractController
{
    /**
     * @Route("/workshop/{id}/register", name="instructor_workshop_register", methods="POST")
     */
    public function workshopRegister(UserRepository $userRepository, WorkshopRepository $workshopRepository, 
                                    Workshop $workshop, Request $request, EntityManagerInterface $entityManager, MailerInterface $mailer)
    {
        $userEmail = $request->getSession()->get('_security.last_username');
        $user = $userRepository->findOneBy(['email' => $userEmail]);

        $user_workshop = $workshopRepository->findWorkshopRegistered($user->getId(), $workshop->getId());

        if (!$user_workshop) {
            $user->addWorkshop($workshop);
            $workshop->addCurrentRegistered();
            $entityManager->flush();

            $email = (new TemplatedEmail())
                ->from('ask@lesmills.com.au')
                ->to($userEmail)
                ->subject('Workshop Registration Invoice ∙ Les Mills Asia Pacific')
                ->htmlTemplate('email/workshop_register_email.html.twig')
                ->context([
                    'workshop' => $workshop,
                    'user' => $user
                ]);

            $mailer->send($email);

            $this->addFlash('success', 'You have successfully registered this workshop! Please check your email for the workshop ticket!');
        } else {
            $this->addFlash('success', 'You have already registered this workshop, you can\'t register again!');
        }

        return $this->redirectToRoute('workshop_detail', ['id' => $workshop->getId()]);
    }

    /**
     * @Route("/workshop/{id}/detail", name="workshop_detail")
     */
    public function register(Workshop $workshop): Response
    {
        return $this->render('workshop/show.html.twig', [
            'workshop' => $workshop
        ]);
    }

}

symfony/templates/workshop/_admin_secondary_btns.html.twig
<div class="dropdown card-widgets">
    <a href="#" class="dropdown-toggle arrow-none" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="dripicons-dots-3"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-end">
        <form action="{{ path('admin_workshop_edit', { id: workshop.id }) }}" method="POST">
            <button class="dropdown-item"><i class="mdi mdi-pencil me-1"></i>Edit</button>
        </form>

        <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#warning-alert-modal"><i class="mdi mdi-delete me-1"></i>Delete</button>
        
        <button class="dropdown-item"><i class="mdi mdi-email-outline me-1"></i>Invite</button>
    </div>

    <div id="warning-alert-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body p-4">
                    <div class="text-center">
                        <i class="dripicons-warning h1 text-danger"></i>
                        <h4 class="mt-3">You are going to delete this workshop, are you sure? </h4>
                        <form action="{{ path('admin_workshop_remove', { id: workshop.id }) }}" method="POST">
                            <button class="btn btn-danger my-2" data-bs-dismiss="modal" formmethod="post">Yes, delete it.</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

symfony/templates/workshop/_instructor_control.html.twig
{% if workshop.statusCode == 1 and workshop.remainingCapacity > 0 %}
    <a href="{{ path('workshop_detail', {'id': workshop.id }) }}" class="d-inline-block btn btn-success float-right" style="width: 50%;">Register</a>
{% elseif workshop.statusCode == 1 and workshop.remainingCapacity <= 0 %}
    <button type="button" class="d-inline-block btn btn-danger float-right" style="width: 50%; cursor: not-allowed;" disabled="disabled">Booked out</button>
{% elseif  workshop.statusCode == 0 %}
    <button type="button" class="d-inline-block btn btn-primary float-right" style="width: 50%; cursor: not-allowed;" disabled="disabled">Ongoing</button>
{% elseif  workshop.statusCode == -1 %}
    <button type="button" class="d-inline-block btn btn-secondary float-right" style="width: 50%; cursor: not-allowed;" disabled="disabled">Finished</button>
{% endif %}

symfony/templates/workshop/_workshop_attachments.html.twig
<div class="card">
    <div class="card-body">
        <h5 class="card-title mb-3">Files</h5>

        <div class="card mb-1 shadow-none border">
            <div class="p-2">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <div class="avatar-sm">
                            <span class="avatar-title rounded">
                                .ZIP
                            </span>
                        </div>
                    </div>
                    <div class="col ps-0">
                        <a href="javascript:void(0);" class="text-muted fw-bold">Hyper-admin-design.zip</a>
                        <p class="mb-0">2.3 MB</p>
                    </div>
                    <div class="col-auto">
                        <!-- Button -->
                        <a href="javascript:void(0);" class="btn btn-link btn-lg text-muted">
                            <i class="dripicons-download"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-1 shadow-none border">
            <div class="p-2">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <img src="{{ asset('images/workshops/workshop-1.jpg') }}" class="avatar-sm rounded" alt="file-image">
                    </div>
                    <div class="col ps-0">
                        <a href="javascript:void(0);" class="text-muted fw-bold">Dashboard-design.jpg</a>
                        <p class="mb-0">3.25 MB</p>
                    </div>
                    <div class="col-auto">
                        <!-- Button -->
                        <a href="javascript:void(0);" class="btn btn-link btn-lg text-muted">
                            <i class="dripicons-download"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-0 shadow-none border">
            <div class="p-2">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <div class="avatar-sm">
                            <span class="avatar-title bg-secondary text-light rounded">
                                .MP4
                            </span>
                        </div>
                    </div>
                    <div class="col ps-0">
                        <a href="javascript:void(0);" class="text-muted fw-bold">Admin-bug-report.mp4</a>
                        <p class="mb-0">7.05 MB</p>
                    </div>
                    <div class="col-auto">
                        <!-- Button -->
                        <a href="javascript:void(0);" class="btn btn-link btn-lg text-muted">
                            <i class="dripicons-download"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

symfony/templates/workshop/_workshop_comments.html.twig
<div class="card">
    <div class="card-body">
        <h4 class="mt-0 mb-3">Comments (258)</h4>

        <textarea class="form-control form-control-light mb-2" placeholder="Write message" id="example-textarea" rows="3"></textarea>
        <div class="text-end">
            <div class="btn-group mb-2">
                <button type="button" class="btn btn-link btn-sm text-muted font-18"><i class="dripicons-paperclip"></i></button>
            </div>
            <div class="btn-group mb-2 ms-2">
                <button type="button" class="btn btn-primary btn-sm">Submit</button>
            </div>
        </div>

        <div class="d-flex align-items-start mt-2">
            <img class="me-3 avatar-sm rounded-circle" src="{{ asset('images/profile/user-6.jpg') }}" alt="Generic placeholder image">
            <div class="w-100 overflow-hidden">
                <h5 class="mt-0">Jeremy Tomlinson</h5>
                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in
                vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis
                in faucibus.
        
                <div class="d-flex align-items-start mt-3">
                    <a class="pe-3" href="#">
                        <img src="{{ asset('images/profile/user-7.jpg') }}" class="avatar-sm rounded-circle" alt="Generic placeholder image">
                    </a>
                    <div class="w-100 overflow-hidden">
                        <h5 class="mt-0">Kathleen Thomas</h5>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in
                        vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue
                        felis in faucibus.
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center mt-2">
            <a href="#" class="text-danger">Load more </a>
        </div>
    </div>
</div>

symfony/templates/workshop/_workshop_info.html.twig
<div class="card d-block">
    <div class="card-body">
        <div class="dropdown float-end">
            <a href="#" class="dropdown-toggle arrow-none card-drop" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="dripicons-dots-3"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-end">
                <!-- item-->
                <a href="#" class="dropdown-item"><i class="mdi mdi-pencil me-1"></i>Edit</a>
                <!-- item-->
                <a href="#" class="dropdown-item"><i class="mdi mdi-delete me-1"></i>Delete</a>
                <!-- item-->
                <a href="#" class="dropdown-item"><i class="mdi mdi-email-outline me-1"></i>Invite</a>
                <!-- item-->
                <a href="#" class="dropdown-item"><i class="mdi mdi-exit-to-app me-1"></i>Leave</a>
            </div>
        </div>
        <!-- project title-->
        <h3 class="mt-0">
            {{ workshop.name }}
        </h3>
        <div class="badge bg-secondary text-light mb-3">Ongoing</div>

        <h5>Workshop Overview:</h5>

        <p class="text-muted mb-2">
            With supporting text below as a natural lead-in to additional contenposuere erat a ante. Voluptates, illo, iste itaque voluptas
            corrupti ratione reprehenderit magni similique? Tempore, quos delectus asperiores libero voluptas quod perferendis! Voluptate,
            quod illo rerum? Lorem ipsum dolor sit amet.
        </p>

        <p class="text-muted mb-4">
            Voluptates, illo, iste itaque voluptas corrupti ratione reprehenderit magni similique? Tempore, quos delectus asperiores
            libero voluptas quod perferendis! Voluptate, quod illo rerum? Lorem ipsum dolor sit amet. With supporting text below
            as a natural lead-in to additional contenposuere erat a ante.
        </p>

        <div class="row">
            <div class="col-md-2">
                <div class="mb-2">
                    <h5>Start Date</h5>
                    <strong> {{ workshop.startsAt|date('Y-m-d H:i') }} </strong>
                    {# <p>17 March 2018 <small class="text-muted">1:00 PM</small></p> #}
                </div>
            </div>
            <div class="col-md-2">
                <div class="mb-2">
                    <h5>End Date</h5>
                    <strong> {{ workshop.endsAt|date('Y-m-d H:i') }} </strong>
                    {# <p>22 December 2018 <small class="text-muted">1:00 PM</small></p> #}
                </div>
            </div>
            <div class="col-md-2">
                <div class="mb-2">
                    <h5>Location</h5>
                    <p>{{ workshop.location }}</p>
                </div>
            </div>
            <div class="col-md-2">
                <div class="mb-2">
                    <h5>Capacity</h5>
                    <p>{{ workshop.capacity }}</p>
                </div>
            </div>
            <div class="col-md-2">
                <div class="mb-2">
                    <h5>Price</h5>
                    <p>Free</p>
                </div>
            </div>
        </div>

        <div id="tooltip-container">
            <form action="{{ path('instructor_workshop_register', { id: workshop.id }) }}" method="POST">
                <h5>Instructors Registered:</h5>
                <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="Mat Helme" class="d-inline-block">
                    <img src="{{ asset('images/profile/user-1.jpg') }}" class="rounded-circle img-thumbnail avatar-sm" alt="friend">
                </a>

                <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="Michael Zenaty" class="d-inline-block">
                    <img src="{{ asset('images/profile/user-2.jpg') }}" class="rounded-circle img-thumbnail avatar-sm" alt="friend">
                </a>

                <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="James Anderson" class="d-inline-block">
                    <img src="{{ asset('images/profile/user-3.jpg') }}" class="rounded-circle img-thumbnail avatar-sm" alt="friend">
                </a>

                <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="Mat Helme" class="d-inline-block">
                    <img src="{{ asset('images/profile/user-4.jpg') }}" class="rounded-circle img-thumbnail avatar-sm" alt="friend">
                </a>

                <a href="#" data-bs-container="#tooltip-container" data-bs-toggle="tooltip" data-bs-placement="top" title="Michael Zenaty" class="d-inline-block">
                    <img src="{{ asset('images/profile/user-5.jpg') }}" class="rounded-circle img-thumbnail avatar-sm" alt="friend">
                </a>

                <a href="#" class="d-inline-block text-dark fw-bold ms-2">
                    +{{ workshop.currentRegistered - 4 }} more
                </a>

                <button type="submit" class="d-inline-block btn btn-success float-right" style="width: 50%;">Register</button>
            </form>
        </div>
    </div>
</div>

symfony/templates/workshop/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WorkshopController!{% endblock %}

{% block main_content %}
<h1> Here is the {{ slug }} Workshop Register page </h1>
{% endblock %}

symfony/templates/workshop/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WorkshopController!{% endblock %}

{% block page_title %}
    {{ include('_page_title.html.twig', {
        breadcrumb_primary: 'Hyper',
        breadcrumb_second: 'Workshops',
        breadcrumb_active: 'Workshop Details',
        secondary_path: 'homepage',
        page_title: 'Workshop Details'
    })}}
{% endblock %}

    
{% block content_block %}
    <div class="row">
        <div class="col-xxl-8 col-lg-6">
            {{ include('workshop/_workshop_info.html.twig')}}
            {{ include('workshop/_workshop_comments.html.twig')}}
        </div>

        <div class="col-xxl-4 col-lg-6">
            {{ include('workshop/_workshop_attachments.html.twig') }}
        </div>
    </div>
{% endblock %}